version: '3.7'

services:
         portainer:
              image: portainer/portainer
              container_name: portainer
              volumes:
                     - /var/run/docker.sock:/var/run/docker.sock
                     - /home/turboscript/shared/Docker/vid-tuts/portrainer:/data
              ports:
                     - 8000:8000
                     - 9000:9000
              restart: always
         nginx:
              image: nginx
              container_name: nginx
              volumes:
                     - /home/turboscript/shared/Docker/vid-tuts/portainer/nginx/:/usr/share/nginx/html
              ports:
                     - 9999:80
         wildfly:
              image: jboss/wildfly
              container_name: wildfly_pri
              volumes:
                     - /var/run/docker.sock:/var/run/docker.sock
                     - /home/turboscript/shared/Docker/vid-tuts/portainer/wildfly:/home
              command: bash wildfly_install_final.sh
              ports:
                     - 9998:8080
                     - 9990:9990
              environment:
                     - WILDFLY_PASSWORD=password
              restart: unless-stopped                  
         jenkins:
              image: jenkins/jenkins:lts-jdk11
              privileged: true
              user: root
              container_name: jenkins
              volumes:
                     - /home/turboscript/shared/Docker/vid-tuts/Jenkins/jenkins_home:/var/jenkins_home
                     - /var/run/docker.sock:/var/run/docker.sock
                     - /usr/local/bin/docker:/usr/local/bin/docker
              ports:
                     - 9997:8080
                     - 50000:50000
       #   sql-server-db:
       #        container_name: sql-server-database
       #        image: mcr.microsoft.com/mssql/server:2019-latest
       #        ports:
       #               - "1433:1433"
       #        environment:
       #               SA_PASSWORD: "t35t@BIRU"
       #               ACCEPT_EULA: "Y"
       #        # volumes:
       #        #        - /home/turboscript/shared/Docker/vid-tuts/sql-server:
       #        restart: unless-stopped
         nagios:
              image: jasonrivers/nagios:latest
              container_name: nagios
              volumes:
                     - /home/turboscript/shared/Docker/vid-tuts/portainer/nagios:/opt/nagios/etc
              ports:
                     - 9996:80
              restart: unless-stopped